### ISSUE TITLE
Database migration fails on new buffalo project

### ISSUE THREAD

**Issue by tobiashienzsch** [gobuffalo/buffalo-auth#32]
Hi,

I created a completely empty buffalo project using version v0.13.12. I then followed the guide for buffalo-auth, so:

```sh
cd $PROJECT_ROOT
go get -u github.com/gobuffalo/buffalo-auth
buffalo g auth
```
No problems here. I then tried to migrate the database with:

 ```sh 
buffalo pop migrate 
``` 

The **error** I got was:

 ```sh 
problem inserting migration version 1547343428200944647: pq: value too long for type character varying(14)
``` 
I checked, no table "users" was created, when starting the Dev server I get a 500 response.

I'm running PostgreSQL latest inside docker, any ideas what the problem could be?

Thanks,
Toby

**Comment by lukasschlueter** [comment]
This should be the same bug as #28, which was fixed in #29 

`buffalo-auth` since didn't get a version bump, which is why `go get` still fetches the old version without the fix.

If you're using go modules, running `go get -u github.com/gobuffalo/buffalo-auth@754fd3d` should work as a quick workaround.

I'll test this again and hope to be able to push the version to 1.0.4 soon.

**Comment by markbates** [comment]
I’ll push a release today.

**Comment by markbates** [comment]
released.

-----------
Mark Bates

**Comment by stanislas-m** [comment]
This should be fixed with the release, please reopen if you still have the issue.
